[project]
name = "tapl"
version = "0.1.0"
description = "Tim's Awesome Programming Language - Including the Compilers"
authors = [{"name" = "Tim Klein Nijenhuis", "email" = "tim@hetorus.nl"}]
license = "MIT"
readme = "README.md"
requires-python = ">=3.14"
dependencies = []

[project.scripts]
tapl-compyler = "compyler.__main__:main"

[tool.setuptools.packages.find]
where = ["src/compilers"]

[tool.setuptools.package-data]
compyler = ["templates/*", "stdlib/*"]

[tool.uv]
package = true

[tool.black]
line-length = 120

[dependency-groups]
dev = [
    "pytest>=8.4.0",
    "pytest-watcher>=0.6.3",
]
